### PR TITLE
#24 CreateEntity Blog, Category, PaymentAccount

### PR DESCRIPTION
**Pull request by Jayus52Hz**
Complete Create Entity, Impl, DAO Blog, Category, PaymentAccount

### CODE REVIEW

**Review by DOCUTEE — COMMENTED** [review]
Bổ sung service nhé Thịnh

**Review by DOCUTEE — CHANGES_REQUESTED** [review]
+ Thịnh không push folder .vs lên
+ Thêm service nữa

**Comment by Jayus52Hz** [comment]
#24 Xoa file vs, hoan thanh task

**Review by DOCUTEE — APPROVED** [review]
ok

**Pull request merged**
